export const EErrors = {
    ROUTING_ERROR: 1,
    INVALID_PARAM: 2,
    INSUFFICIENT_STOCK: 3,
    NOT_EXISTENT_PROPERTY: 4,
    INVALID_QUANTITY: 5,
    EMPTY_ARRAY_PRODUCTS: 6,
    NOT_EXISTENT_PRODUCT: 7
}

